apiVersion: apps/v1
kind: Deployment
metadata:
  name: #
  namespace: #
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #
  template:
    metadata:
      labels:
        app: #
    spec:
      containers:
      - name: #
        image: #
        imagePullPolicy: Always
